url: "https://isuserselva.github.io/sahasrait.github.io/"
baseurl: ""
permalink: pretty
title: 'Sahasra IT Pty Ltd'

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

logo:
  desktop: "images/logo/logo.svg"
  desktop_width: 120
  desktop_height: 32
  
sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
#  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
